print("Welcome to the tip calculator")
bill = input("What was the total bill? $")
percentage = input("What percentage tip would you like to give? 10, 12, or 15? ")
num_people = input("How many people to split the bill? ")
final_result = float(bill) * (1 + (int(percentage) / 100) ) / int(num_people)
print(f"Each person should pay ${round(final_result,2)}")
